apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: test-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
         - image: nginx:alpine
           name: frontend-application
           ports:
            - containerPort: 5000
