apiVersion: v1
kind: Pod
metadata:
 labels:
  test: liveness
 name: liveness-exec
spec:
 containers:
 - name: liveness
   image: busybox
   args:
   - /bin/ash
   - -c
   - touch /temp/healthy; sleep 30; rm -rf /temp/healthy; sleep 600
   livenessProbe:
    httpGet:
     path: /healthz
     port: 8080
     httpHeaders:
     - name: X-Custom-Header
       value: Awesome
    initialDelaySeconds: 15
    failureThreshold: 1
    periodSeconds: 5
