apiVersion: v1
kind: Pod
metadata:
 labels:
  test: startupness
 name: startupness-exec
spec:
 containers:
 - name: startupness
   image: busybox
   args:
   - /bin/ash
   - -c
   - touch /temp/healthy; sleep 30; rm -rf /temp/healthy; sleep 600
   startuoProbe:
    exec:
     command:
     - cat
     - /tmp/healthy
    failureThreshold: 30
    periodSeconds: 10
