apiVersion: v1
kind: Pod
metadata:
 labels:
  test: readiness
 name: readiness-exec
spec:
 containers:
 - name: readiness
   image: busybox
   args:
   - /bin/ash
   - -c
   - touch /temp/healthy; sleep 30; rm -rf /temp/healthy; sleep 600
   readinessProbe:
    exec:
     command:
     - cat
     - /tmp/healthy
    initialDelaySeconds: 15
    failureThreshold: 1
    periodSeconds: 5
